name: Unit Testting

on:
  push:
    branches: [ patch-**, development ]

jobs:
  test:
    runs-on: ubuntu-latest
    container: reactnativecommunity/react-native-android
    steps:
      - uses: actions/checkout@v2

      - name: Install Modules
        run: yarn install

      - name: Build
        run: yarn build --if-present

      - name: Start Testing
        run: yarn test
